### PR TITLE
clang build fix march=native is unsupported

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by Screwtapello** [comment]
Which versions of clang do not support `-march=native`?

```
$ clang --version
Debian clang version 11.0.1-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ clang -march=native -o werder werder.c
$ ls -l werder
-rwxr-xr-x 1 st st 16864 Mar 20 22:40 werder
```

**Comment by devnexen** [comment]
clang/xcode specifically

**Comment by jchv** [comment]
In general, clang does support this flag, so it is not a good idea to not set it whenever clang is being used. Detecting that we’re on a setup that doesn’t support `-march` will require some better detection. For now my workaround for the problem is to just pass `local=false` to make when building on M1.

**Comment by Screwtapello** [comment]
After some scrounging around, I found [an article](https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/compiler-flags-across-architectures-march-mtune-and-mcpu) discussing tuning flags across ARM and x86. Apparently `-march`, `-mcpu` and `-mtune` mean different things, and x86's `-march` is roughly equivalent to ARM's `-mcpu`, it doesn't have anything to do with macOS, and it's not even specific to Clang/LLVM (although GCC is friendlier to x86 compiler flags).

**Comment by devnexen** [comment]
seems to work on Mac M1.

**Comment by Screwtapello** [comment]
Thank you for looking into this! I've made an expanded version of this change in #167, preserving you as the patch author. If you could look over that change and confirm I haven't missed anything, I'll land it.

**Comment by devnexen** [comment]
All good

**Comment by Screwtapello** [comment]
I've merged #167, so higan should build cleanly on M1 Macs by default now. Again, thank you for your help!

**Pull request closed without merging**
