### PR TITLE
ps1 some fixes.

### PR DESCRIPTION
**Pull request by dalmatian128**
GTE patch is implement LZCR to improve GTE support,
another patches is simple bug fixes.

### CODE REVIEW

**Comment by Screwtapello** [comment]
Thank you for figuring this stuff out!

I'm curious about the LZCS change, though - does anybody know how fast this is? Do games have to wait some number of cycles before reading the result from LZCR, or can they literally write to LZCS and read the result back from LZCR in the next instruction?

It seems like the kind of operation that *should* be pretty fast for custom hardware to implement, but I remember that a lot of SNES homebrew failed on real hardware because they assumed multiplication results would be available at the next instruction, since that's what the common emulators of the time did. If we don't know for sure that it's effectively instant, we should at least have a TODO comment or similar.

@asuramaru ? @LukeUsher ? You guys know PSX hardware, can you shed any light on this?

**Comment by dalmatian128** [comment]
I don't know real LZCR cycles.
Experimentally, ps1 games insert two SLL opcodes between writing LZCS and reading LZCR,
so may needs some cycle delay slot ?

**Comment by Screwtapello** [comment]
@asuramaru pointed out on Discord that `SLL r0, r0, 0` (shift register 0 left by 0 bits, storing in register 0) is encoded as all-zeroes, and is the idiomatic way to encode NOP, so that's almost certainly waiting for the result to be ready.

I don't actually know how to make higan delay the answer for two instructions, though, and even if I did the GTE emulation may not (yet) be wired up to operate independently of the CPU, so I won't ask you to figure that out.

Still, if you could add a comment above the LZCS code, along the lines of:

    // FIXME: This result shouldn't be available instantly,
    // most games put two NOPs before reading the result.

...then I think it'll be ready to merge.

**Comment by Screwtapello** [comment]
Thank you again!

**Pull request merged**
