### PR TITLE
SVG icon for byuu

### PR DESCRIPTION
**Pull request by jchv**
Adds an SVG icon and a line in the Makefile for installing it, a la #141.

Not perfect but probably close enough.

| Original | SVG Rendering |
| --- | --- |
|  byuu icon (original) | byuu icon (jchw's SVG rendition) |

### CODE REVIEW

**Comment by ghisvail** [comment]
Looks like there used to be an SVG for icarus in [version 110](https://github.com/higan-emu/higan/blob/v110/icarus/data/icarus.svg), just not located at the usual place. I found it my looking at the ArchLinux packaging once more.

My bad :facepalm:

**Comment by near-san** [comment]
On account of deprecating this build, I suppose we can close this now ...

I will get you the official bsnes and higan SVG files though and attach it to your other issue when I'm at my PC again.

**Comment by ghisvail** [comment]
Le sam. 6 févr. 2021 à 09:56, Near <notifications@github.com> a écrit :

> On account of deprecating this build, I suppose we can close this now ...
>
I have just read your blog post about it. Makes total sense.

> I will get you the official bsnes and higan SVG files though and attach it
> to your other issue when I'm at my PC again.
>
That would be great. Thank you!

**Comment by Screwtapello** [comment]
Closing this issue since the "byuu" UI has been removed from higan; it will continue as part of Near's "ares" project,

**Pull request closed without merging**
