### PR TITLE
higan rebranding

### PR DESCRIPTION
**Pull request by near-san**
This is a rebranding pull request.

Originally, higan started becoming two emulators in one:
* an accuracy-focused, complete GUI focused on preservation
* a performance-focused, simplfied GUI focused on features
The first became known as "higan-ui"; the second as "byuu"

Later on, the ares emulator split off from higan.
The ares emulator's equivalents were "luna" and "lucia".

This rebranding is a counterpart to ares' recent rebranding.
The goal is to cleanly separate these two emulators, going forward:
* higan will fulfill the accuracy-focused, complete emulation role
* ares will fulfill the performance-focused, simplified emulation role

Therefore, this pull request makes the following changes to higan:
* removes the "byuu" user interface
* renames the "higan-ui" user interface to simply "higan"
** updates the resource/ files and install/config directories to "higan"
* removes the Nintendo 64 and PlayStation cores
** this is because they are not accuracy-focused and never will be
** which is because they are too demanding for true cycle-accuracy
* removes N64 and PS1 support from icarus
** so that unsupported systems don't appear in the import tool
* merges the extras/ folder back to one level (since "byuu" was removed)
* updates Cirrus and github workflows to not build "byuu"
* removes the Super Famicom, PC Engine, and Mega Drive scanline renderers
** as they are not accurate compared to the pixel renderers
* removes the PC Engine audio decimation performance hack
* removes the Game Boy Advance lazy-synchronization performance hack
* removes the profile= build directive
* updates my name to Near in various readme files and source code headers

Not related to this diff, but from the other side with ares:
* the "luna" user interface was removed
* the "lucia" user interface was renamed to simply "ares"
* it is build with the performance profiles
* it now contains the N64 and PS1 cores exclusively

With these changes, a lot of confusion and overlap is eliminated.
Each emulator now stands on its own and serves different purposes.

This is a major restructuring, so it's possible this PR isn't perfect.
We may need to commit a few small fixes after merging this to finish the task.

### CODE REVIEW

**Comment by Kawa-oneechan** [comment]
Sounds good to me. Screw?

**Comment by Screwtapello** [comment]
The changes look good to me!

I squashed the commits and edited the commit message a bit; assuming all the builds pass, I'll hit the merge button unless somebody beats me to it.

**Comment by Screwtapello** [comment]
Thank you, Near, for doing all the hard work for this PR!

**Comment by near-san** [comment]
Thank you! I'm very happy you guys are okay with this proposal.

I made quite a mess of the naming, but I really have a good feeling about this and the new domains getting us back on track with a simpler story. The key will just be to stick with this consistently and in a couple years it should work itself out.

We can close #6 #7 #27 #30 #76 #77 #83 #119 #127 here now. We can also simplify #39 now.

**Pull request merged**
