### PR TITLE
WonderSwan: One Piece Grand Battle Swan Colosseum SwanCrystal EEPROM dump

### PR DESCRIPTION
**Pull request by up-n-atom**
An unsanitized EEPROM dump from a One Piece Grand Battle Swan Colosseum SwanCrystal. In which it contains the custom bootsplash for the handheld.

Copy to the SwanCrystal systems directory and rename to save.eeprom

### CODE REVIEW

**Comment by up-n-atom** [comment]
OnePieceBootsplash

Attached is a preview of the bootsplash.

**Comment by Kawa-oneechan** [comment]
This seems legally questionable. But what do I know?

**Comment by up-n-atom** [comment]
That's a legitimate concern. I will pull the request in the meantime.

**Comment by Screwtapello** [comment]
There absolutely should be a place to archive clean EEPROM dumps; as well as being useful for emulation (so the user can experience more of what it was like to boot up a WonderSwan for the first time), according to https://github.com/Godzil/splashbuilder custom boot screens can included arbitrary graphics, audio, and code, so you could even make a little game (as long as it runs in less than 255 frames).

However, I don't think higan is the right places for such an archive, because of the whole copyright thing. Perhaps No-Intro would be the best place for this kind of thing?

**Pull request closed without merging**
